openapi: 3.0.0
info:
  title: WasaPhoto
  description: |
    API for the project the course of WASA
  version: 0.0.1
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userid'
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userid'
                
  /users:
    get:
      tags: ['user']
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
                  
  /users/{userid}:
    parameters:
      - $ref: '#/components/parameters/userid'
    get:
      tags: ['user']
      summary: ask for the mainstream of the userid
      operationId: getMyStream
      responses:
        '200':
          description: return the photos of all the following in reverse chronological order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/photo'
    
  /users/{userid}/photos:
    parameters:
      - $ref: '#/components/parameters/userid'
    post:
      tags: ["photo", 'user']
      summary: uploads a picture for the user
      operationId: uploadPhoto
      requestBody:
        description: the photo to be uploaded
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/photo'
        required: true
      responses:
        '200':
          description: succesfull operation, returns the id of the new photo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/photoid'
  
  /users/{userid}/photos/{photoid}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - $ref: '#/components/parameters/photoid'
    delete:
      tags: ['photo', 'user']
      summary: deletes the photo
      operationId: deletePhoto
      responses:
        "200":
          description: succesfull operation
    
  /users/{userid}/photos/{photoid}/comments:
      parameters:
        - $ref: '#/components/parameters/userid'
        - $ref: '#/components/parameters/photoid'
      post:
        tags: ['user', "photo", 'comment']
        summary: uploads a comment on the picture
        operationId: commentPhoto
        requestBody:
          description: the photo to be uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
          required: true
        responses:
          '200':
            description: succesfull operation, returns id of the comment
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/commentid'
                  
  /users/{userid}/photos/{photoid}/comments/{commentid}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - $ref: '#/components/parameters/photoid'
      - $ref: '#/components/parameters/commentid'
    delete:
      tags: ['user', "photo", 'comment']
      summary: deletes the comment
      operationId: uncommentPhoto
      responses:
        "200":
          description: succesfull operation
    put:
      tags: ['user', "photo", 'comment']
      summary: modifies the comment
      operationId: modifyComment
      requestBody:
        description: the new comment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comment'
        required: true
      responses:
        '200':
          description: succesfull operation, returns id of the comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commentid'

  /users/{userid}/photos/{photoid}/likes:
    parameters:
      - $ref: '#/components/parameters/userid'
      - $ref: '#/components/parameters/photoid'
    post:
      tags: ['user', "photo", 'like']
      summary: likes the picture, returns '200' if the picture is already liked
      operationId: likePhoto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userid'
        required: true
      responses:
        '201':
          description: succesfull operation, returns id of the like
        '200':
          description: like already exists (idempotent request)
  

  /users/{userid}/photos/{photoid}/likes/{likeid}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - $ref: '#/components/parameters/photoid'
      - $ref: '#/components/parameters/likeid'
    delete:
      tags: ['user', 'photo', 'like']
      summary: unlikes the photo
      operationId: unlikePhoto
      responses:
        "200":
          description: succesfull operation

  /users/{userid}/followers:
    parameters:
      - $ref: '#/components/parameters/userid' 
    post:
      tags: ['user', 'follow']
      summary: add a user to the follower list, returns '200' if the user is already a follower
      operationId: addFollower
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userid'
        required: true
      responses:
        '201':
          description: user added succesfully
        '200':
          description: the user already exists in the followwers list
          
  /users/{userid}/followers/{followinguser}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - in: path
        name: followinguser
        schema:
          $ref: '#/components/parameters/userid'
        required: true
    delete:
      tags: ['user', 'follow']
      summary: deletes the user from the followers likst
      operationId: removeFollower
      responses:
        "200":
          description: succesfull operation
  
  /users/{userid}/following:
    parameters:
      - $ref: '#/components/parameters/userid' 
    post:
      tags: ['user', 'follow']
      summary: add a user to the following list, returns '200' if the user is alrady followed
      operationId: followUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userid'
        required: true
      responses:
        '201':
          description: user followed succesfully
        '200':
          description: user already in the following list

  /users/{userid}/following/{followinguser}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - in: path
        name: followinguser
        schema:
          $ref: '#/components/parameters/userid'
        required: true
    delete:
      tags: ['user', 'follow']
      summary: deletes the user from the followers likst
      operationId: unfollowUser
      responses:
        "200":
          description: succesfull operation
  
  /users/{userid}/banned:
    parameters:
      - $ref: '#/components/parameters/userid' 
    post:
      tags: ['ban', 'user']
      summary: add a user to the banned list, returns '200' if the user is alrady banned
      operationId: banUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userid'
        required: true
      responses:
        '201':
          description: user followed succesfully
        '200':
          description: user already in the following list
  
  /users/{userid}/banned/{banneduser}:
    parameters:
      - $ref: '#/components/parameters/userid'
      - in: path
        name: banneduser
        schema:
          $ref: '#/components/parameters/userid'
        required: true
    delete:
      tags: ['ban', 'user']
      summary: unbans the user
      operationId: unbanUser
      responses:
        "200":
          description: succesfull operation



components:
  parameters:
    
    commentid: 
      name: commentid
      in: path
      description: The comment id
      required: true
      schema:
        $ref: '#/components/schemas/commentid'
    
    userid: 
      name: userid
      in: path
      description: The username of the user
      required: true
      schema:
        $ref: '#/components/schemas/userid'
        
    photoid:
      name: photoid
      in: path
      description: identificative of the photo
      required: true
      schema:
        $ref: '#/components/schemas/photoid'
        
    likeid:
      name: likeid
      in: path
      description: identificative of the like (the username of the person who put like)
      required: true
      schema:
        $ref: '#/components/schemas/like'
        
        
  schemas:
  
    photoid:
      type: string
    
    commentid:
      type: string
      
    like:
      type: object
      properties:
        from:
          $ref: '#/components/schemas/userid'
        photoId:
          $ref: '#/components/schemas/photoid'
          
  
    userid:  
      type: object
      properties:
        name:
          type: string
          example: Maria
          pattern: 'Ë†.*?$'
          minLength: 3
          maxLength: 16
    
    comment:
      type: object
      example: "Che bella foto!!!"
      properties:
        user:
          $ref: '#/components/schemas/userid'
        content:
          type: string
        date:
          type: string
          format: date-time
          
    photo:
      type: object
      properties:
        photoid:
          $ref: '#/components/schemas/photoid'
        image:
          type: string
          format: binary
        user:
          $ref: '#/components/schemas/userid'
        likes: 
          type: array
          items:
            $ref: '#/components/schemas/like'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/comment'
        date:
          type: string
          format: date-time
        likecount:
          type: integer
          default: 0
      required:
        - photoid
        - image
        - user
        - date
        - likeCount
        